on:
  - push

jobs:
  install:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true

      - name: Install deps
        run: pnpm i

      - name: Compile
        run: pnpm -r build

      - name: "Let's Hint!"
        run: |
          node ./chl hint -c hcfg/Light.json -h cache-r.gz -j 4 shstw-rotated.ttf hint-data-r.gz
          node ./chl instruct -c hcfg/Light.json shstw-rotated.ttf hint-data-r.gz shstw-hinted-r.ttf

      - name: Upload hint data
        uses: actions/upload-artifact@v7
        with:
          name: hint-data
          path: |
            cache-r.gz
            hint-data-r.gz

      - name: Upload font
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: shstw-hinted-r.ttf
