on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true

      - name: Install deps
        run: pnpm i

      - name: Compile
        run: pnpm -r build

      - name: esbuild chl-hm-ideograph
        run: |
          cd chl-hm-ideograph
          pnpm exec tsdown
          node esbuild.js

      - name: Upload bundled JS
        uses: actions/upload-artifact@v7
        with:
          name: hm-ideograph-bundled
          path: chl-hm-ideograph/dist
